spring:
  application:
    name: hhplus-tdd-week2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hhplus_tdd_week2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
